syncer:
  sync_offset: 24h
  wait_time: 1s
  resync_delay_after_fail: 1h
  timepad:
    url: https://api.timepad.ru/v1/events.json?limit=100&skip=0&cities=Москва&fields=location,description_short&sort=+starts_at&starts_at_min=2022-10-08T21:00:00
  vk:
    get_events: https://api.vk.com/method/groups.search
    get_events_data: https://api.vk.com/method/groups.getById

postgres:
  host: localhost
  port: 5432
  dbname: friender
  user: postgres
  password: 1234
transport:
  timepad:
    download_limit_bytes: 2000000000
  vk:
    download_limit_bytes: 2000000000
  http:
    connect_timeout: 500ms
    keep_alive: 1m
    max_idle_conns: 0
    max_idle_conns_per_host: 0
    read_write_timeout: 5s
vk:
  access_token: vk1.a.3v18zK0yJZRszF9FRAvhVhACDcDYPqZeeEkaehZ0k-qli2EIioZif1R4mI1cfQuwxH7cqLXG2JmDGHcf4AiTma5MpwGnhyZ3FBWjMbLqlbvCjRk1AbK8_7oWxO0DZBRySBUh2XDWCtXY6SVRRl4gDq07_U3IC-IdASY5nzcVTgZ7-qoib3C8fhoU-6I1U7-e
  group_id: 216524191
  album_id: 287761027
  version: 5.131
blacklist: ['(вы|ты)?бл(е|и)?я.*?',
            '(у|п[оo](д[ьъ]?)?|про|за|на|[оo]т|вы|у|сь|съ|вь|въ|хитр[оo]вы|раз[ьъ]?)?[её]бк?н?[иолуаеёы].*?',
            '(вы|ты)?бл(е|и)?я.*?',
            ' (у|п[оo](д[ьъ]?)?|про|за|на|[оo]т|вы|у|сь|съ|вь|въ|хитр[оo]вы|раз[ьъ]?)?[её]бк?н?[иолуаеёы].*?',
            '(от)?м[уy]д[аиео].*?',
            'д[аоo]лб[аaоo][её].*?',
            '(в|на|от|с|по|ра[зс]|про|о)?п[ие]?зд[юяиуаоецы].*?',
            'п[еи]д[аое]?р.*?',
            'ху[еёй].*?',
            'г[ао]ве?н.*?',
            '(по|на|вы)?сра[кнт].*?',
            'гандо.*?',
            '(vy)?bl(ya|9).*?',
            '(u|pod?|pro|za|na|ot|vy|u|c|v|hitrovy|raz)?ebk?n?[ioluyae].*?',
            '[scс][uyу]k?4?[oiaа].*?',
            '(ot)?mud[aieo].*?',
            'd[ao]lb[ao]e.*?',
            '(na|ot|s|po|ra[sz]|v|pro|o)?p[ie]?zd[uyiaoe].*?',
            'p[ei]d[aoe]?r.*?',
            'g[ao]ve?n.*?',
            '(po|na|vy)?sra[ktn].*?',
            '(na|ni|za|po|do|ot?)?(h|x)(u|y)[lyie].*?',
            'gando.*?',
            '(mother|maza)?fuck.*?',
            '(bul)?shit',
            'suck.*?',
            'bitch.*?',
            'fag(ot)?s?',
            'bastards?',
            'morons?',
            'assholes?']


