syncer:
  sync_offset: 24h
  wait_time: 1s
  resync_delay_after_fail: 1h
  url: https://api.timepad.ru/v1/events.json?limit=100&skip=0&cities=Москва&fields=location,description_short&sort=+starts_at&starts_at_min=2022-10-08T21:00:00
postgres:
  host: localhost
  port: 5432
  dbname: friender
  user: manuel
  password: 0000
transport:
  timepad:
    download_limit_bytes: 2000000000
  http:
    connect_timeout: 500ms
    keep_alive: 1m
    max_idle_conns: 0
    max_idle_conns_per_host: 0
    read_write_timeout: 5s