name: Deploy

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Create env file'
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo $AWS_SECRET_ACCESS_KEY
          make build

      - name: Upload build result main_server
        uses: actions/upload-artifact@v1
        with:
          name: main_server
          path: ./build/main_server

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download bin file api
        uses: actions/download-artifact@v1
        with:
          name: main_server

      - name: Transfer bin api file to server
        uses: appleboy/scp-action@master
        with:
          port: 22
          host: 37.139.33.76
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          source: "main_server"
          target: "~/testfriender/FrienderAPI/build"

      - name: chmod
        uses: appleboy/ssh-action@master
        with:
          host: 37.139.33.76
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          script: |
             chmod -R 755 ~/testfriender/FrienderAPI/build/main_server
             sudo service vkevents restart

